server:
    port: 8080

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
    thymeleaf:
        cache: false

logging:
    level:
        org:
            playentropy:
                circuit: DEBUG
            springframework:
                web:
                    socket: TRACE
                messaging: TRACE


